#161 Allow the creation of custom (opened) TCP endpoints.
MSOpenTech/vagrant-azure pull request #162
Opened 2017-02-16 23:53 UTC by ddanciu

This enables the setup of custom opened ports. 
At the moment it allows only one interval.

In the future it should support multiple port intervals (comma separated).

2017-02-16 23:54 UTC, azurecla commented
Hi __@ddanciu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

2017-02-17 00:55 UTC, devigned commented on templates/arm/deployment.json.erb
> +        <% end %>
Looks like has_tcp_endpoints is only being applied to Linux VMs, or are my eyes playing tricks on me?

2017-02-17 06:34 UTC, ddanciu commented on templates/arm/deployment.json.erb
> +        <% end %>
Indeed. Apparently haven't thought it far enough. 
Will update it.

2017-02-17 06:37 UTC, azurecla commented
__@ddanciu__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

2017-02-17 15:09 UTC, devigned commented on templates/arm/deployment.json.erb
> +        <% end %>
Let me know when you'd like me to review the PR. Thank you for attempting this feature.

2017-02-19 16:43 UTC, ddanciu commented on templates/arm/deployment.json.erb
> +        <% end %>
Hi @devigned , Can you please have a look. I would love some feedback. 

Thanks,
Dan

2017-02-20 18:08 UTC, devigned requested changes
Looks better -- I think this is almost there. I've included a few items to clean up.

2017-02-20 18:08 UTC, devigned commented on README.md
> +* `tcp_endpoints`: (Optional) The custom inbound security rules part of network security group (a.k.a. opened tcp endpoints). Allows specifying one or more intervals in the form '8000-9000, 9100-9200
Perhaps, this should be an array of strings. String parsing of the array will be a bit ambiguous where the array syntax only requires the understanding and parsing of the port range strings (start_port-end_port).

```ruby
tcp_endpoints = ['8000-9000', '9100-9200']
```

2017-02-20 18:08 UTC, devigned commented on lib/vagrant-azure/action/run_instance.rb
> +            endpoints = {}
endpoints here should be an `[]` rather than a hash `{}`.

2017-02-20 18:08 UTC, devigned commented on templates/arm/deployment.json.erb
> +              "priority": <%= 133 + index %>,
Per the docs for network security group rule priority (https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-nsg#Nsg-rules) rule priority must be between `Number between 100 and 4096`. I think this is an edge case, but might warrant an error if the user has `endpoints.length * 133 > 4096`.

2017-02-24 21:23 UTC, ddanciu commented
@devigned, any other feedback is appreciated.
Also, would it be possible to have this merged, we are planning on using  this feature for a project starting next week.

Thanks,
Dan

2017-02-24 23:03 UTC, devigned approved these changes

2017-02-24 23:04 UTC, merged

2017-02-24 23:04 UTC, devigned commented
LGTM! Thank you for the contribution.